# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9560adf6fbf7abbb5e33a72e86f5f238d65f4502593388890ce263df9ebc4442c43d12f41c73c8b1bdf498e96c247361f9276d9a096c5da6c1dae17b8839f8f4

test:
  secret_key_base: 5a9a61b5343e9198c089ac45b76bb5bdd6c3775891030e1c62bd774d7d9a476449fb6c70adc5857da460ff3f71fc1f8591b605009984578994af2c0b3f442180

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
